### ISSUE TITLE
关于高校域名的问题

### ISSUE THREAD

**Issue by risshun** [IPv6-CN/network-testing-domains#1]
上海交大和华东理工的域名并非是www开头，而是www6。

即
`www6.sjtu.edu.cn`
`www6.ecust.edu.cn`

**Comment by inntran** [comment]
不会做出修改的几个原因：
1. 此处只收集“域名”，而不是主机名
2. 从用户的角度考虑，输入网址时为什么不可以使用已有的 convention，即 www 开头的域名？
3. 从网站管理员角度，使用 www6 和 ipv6 域名没有本质不同，都是降低了主要域名“www” 设置 IPv6 解析的风险，在我看来等于逃避问题。
4. 我考虑过在实现中给予 www6 和 ipv6 开头的主机名部分 credit，但是这样能否督促网站管理员部署符合互联网通行的 DNS 记录？目前还没有结论。
